services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: blogging-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: blogging-app
    networks:
      - blogging-network

  # Backend Service
  backend:
    image: avinash0101/blogging-backend:latest
    container_name: blogging-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/blogging-app
    depends_on:
      - mongodb
    networks:
      - blogging-network

  # Frontend Service
  frontend:
    image: avinash0101/blogging-frontend:latest
    container_name: blogging-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - blogging-network

networks:
  blogging-network:
    driver: bridge

volumes:
  mongodb_data:
